name: Integration Test

on:
  push:
    branches: [develop, master, ci, 'v1*', compatibility-changes]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:

jobs:
  godwoken-tests:
    uses: nervosnetwork/godwoken-tests/.github/workflows/reusable-integration-test-v1.yml@develop
    with:
      # github.ref: The branch or tag ref that triggered the workflow run. For branches this is the format refs/heads/<branch_name>, and for tags it is refs/tags/<tag_name>.
      kicker_ref: ${{ github.ref }}
